#!/bin/bash

. $SNAP/snap/command-chain/snapcraft-runner

certbot renew \
    --work-dir="$SNAP_DATA/certbot/work" \
    --logs-dir="$SNAP_DATA/certbot/logs" \
    --config-dir="$SNAP_DATA/certbot/config" \
    --config="$SNAP_DATA/certbot/cli.ini" \
    --tls-sni-01-port=8888

$SNAP/bin/cat-certs
$SNAP/bin/reload
